language: node_js
node_js: node_js
  - 13

services:
  - docker

#Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"

script: 
  - sudo docker --version # print the version for logging
  - sudo docker build -t simple-node .
  - sudo docker tag simple-node testrungirl/simple-node:latest

# Task to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs/
after_success:
  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
  - sudo docker push testrungirl/simple-node